{% set name = "magicgui" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3dd3b6d16fb5c2188950b495524325649a8e7990bbf2d745ded38ada73973e8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7
    - docstring_parser
    - psygnal >=0.1.3
    - qtpy >=1.7.0
    - typing_extensions

test:
  requires:
    - pyside2
  imports:
    - magicgui

about:
  home: https://github.com/napari/magicgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: build GUIs from functions, using magic.
  doc_url: https://napari.org/magicgui
  dev_url: https://github.com/napari/magicgui

extra:
  recipe-maintainers:
    - k-dominik
    - tlambert03
