{% set name = "magicgui" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8c1c7ed281e62ec858771a76515abd705dbe3d46da2ee834ce6983a4403b94d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.8.0
    - hatch-vcs
  run:
    - python >=3.8
    - docstring_parser >=0.7
    - psygnal >=0.6.1
    - qtpy >=1.7.0
    - superqt >=0.4.0
    - typing_extensions >=4.1.0
    - pyconify >=0.1.4

test:
  requires:
    - pyside2
  imports:
    - magicgui

about:
  home: https://github.com/pyapp-kit/magicgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Build GUIs from python types.
  doc_url: https://pyapp-kit.github.io/magicgui/
  dev_url: https://github.com/pyapp-kit/magicgui

extra:
  recipe-maintainers:
    - tlambert03
