{% set name = "magicgui" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56dbe28afc526809e09932cd6caad8fc1a8305fe66c8feca16f797a04b5aee7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.8.0
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - docstring_parser >=0.7
    - psygnal >=0.6.1
    - qtpy >=1.7.0
    - superqt >=0.6.1
    - typing_extensions >=4.6
    - pyconify >=0.1.4

test:
  requires:
    - pyside2
    - python {{ python_min }}
  imports:
    - magicgui

about:
  home: https://github.com/pyapp-kit/magicgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Build GUIs from python types.
  doc_url: https://pyapp-kit.github.io/magicgui/
  dev_url: https://github.com/pyapp-kit/magicgui

extra:
  recipe-maintainers:
    - tlambert03
