{% set name = "magicgui" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f05ba85fe8be39d36975dfb25e53cae9e17a5ccc5c15fb68334683735cdce83

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python
    - qtpy >=1.7.0

test:
  requires:
    - pyside2
  imports:
    - magicgui

about:
  home: https://github.com/napari/magicgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: build GUIs from functions, using magic.
  doc_url: https://magicgui.readthedocs.io/en/latest/
  dev_url: https://github.com/napari/magicgui

extra:
  recipe-maintainers:
    - k-dominik
    - tlambert03
