{% set name = "magicgui" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3279b7e78e690f35c18b61065cf3234c4f05a973e485dc3c696446a68a59c665

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.8.0
    - hatch-vcs
  run:
    - python >=3.8
    - docstring_parser >=0.7
    - psygnal >=0.5.0
    - qtpy >=1.7.0
    - superqt >=0.4.0
    - typing_extensions

test:
  requires:
    - pyside2
  imports:
    - magicgui

about:
  home: https://github.com/pyapp-kit/magicgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Build GUIs from python types.
  doc_url: https://pyapp-kit.github.io/magicgui/
  dev_url: https://github.com/pyapp-kit/magicgui

extra:
  recipe-maintainers:
    - k-dominik
    - tlambert03
